# Import Required Libraries

In [1]:
import pandas as pd
import numpy as np

# Dataset
from sklearn.datasets import load_breast_cancer

# Train Test Split
from sklearn.model_selection import train_test_split

# Feature Scaling
from sklearn.preprocessing import StandardScaler

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load Dataset
#### Loads dataset into variable data.

#### X

#### Contains input features like:

#### -mean radius
#### -mean texture
#### -mean perimeter etc.
#### y

#### Contains output labels:

#### -0 = Malignant (Cancerous)
#### -1 = Benign (Non-cancerous)

In [2]:
data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target)

# View Dataset

#### X.head()

#### Shows first 5 rows of features.

#### y.head()

#### Shows first 5 target values.

In [3]:
print(X.head())
print(y.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0           

# Check Missing Values

#### This checks if any values are missing.

#### Result:

#### This dataset has no missing values.

In [11]:
print(X.isnull().sum())

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64


# Feature Scaling

In [5]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train Test Split

#### test_size=0.2

#### 20% data for testing.

#### random_state=42

#### Same split every time.

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

# Create Models

In [7]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "KNN": KNeighborsClassifier()
}

# Train and Evaluate Models

In [8]:
results = {}

for name, model in models.items():
    
    # Train Model
    model.fit(X_train, y_train)
    
    # Predict
    y_pred = model.predict(X_test)
    
    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    
    results[name] = acc
    
    print("Model:", name)
    print("Accuracy:", acc)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("-"*50)

Model: Logistic Regression
Accuracy: 0.9736842105263158
[[41  2]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

--------------------------------------------------
Model: Decision Tree
Accuracy: 0.9210526315789473
[[39  4]
 [ 5 66]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90        43
           1       0.94      0.93      0.94        71

    accuracy                           0.92       114
   macro avg       0.91      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114

--------------------------------------------------
Model: Random Forest
Accuracy: 0.9649122807017544
[[40  3]
 [ 1 70]]
              precision    reca

C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\ProgramData\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
        "wmic CPU Get NumberOfCores /Format:csv".split(),
        capture_output=True,
        text=True,
    )
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^

# Compare Results

In [9]:
result_df = pd.DataFrame(results.items(), columns=["Model", "Accuracy"])
print(result_df.sort_values(by="Accuracy", ascending=False))

                 Model  Accuracy
0  Logistic Regression  0.973684
3                  SVM  0.973684
2        Random Forest  0.964912
4                  KNN  0.947368
1        Decision Tree  0.921053


# Best and Worst Model

In [10]:
best_model = result_df.loc[result_df["Accuracy"].idxmax()]
worst_model = result_df.loc[result_df["Accuracy"].idxmin()]

print("Best Model:")
print(best_model)

print("Worst Model:")
print(worst_model)

Best Model:
Model       Logistic Regression
Accuracy               0.973684
Name: 0, dtype: object
Worst Model:
Model       Decision Tree
Accuracy         0.921053
Name: 1, dtype: object


# Final Conclusion
### Best Model: Random Forest / SVM
### Worst Model: Decision Tree

## Because:

### Random Forest combines many trees.
### SVM handles complex boundaries.
### Decision Tree may overfit.